<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('CellaVita'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'))
            ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="glyphicon glyphicon-bar glyphicon-white"></span>
                        <span class="glyphicon glyphicon-bar glyphicon-white"></span>
                        <span class="glyphicon glyphicon-bar glyphicon-white"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><span class="glyphicon glyphicon-home glyphicon-white"></span>&nbsp;<?php echo $this->translate('CellaVita') ?></a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="<?php if ($this->optionMenu == 'cadastro') echo 'active' ?>"><a href="<?php echo $this->url('donor') ?>"><span class="glyphicon glyphicon-pencil glyphicon-white"></span>&nbsp;<?php echo $this->translate('Doadores') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="<?php if ($this->optionMenu == 'cultura') echo 'active' ?>"><a href="<?php echo $this->url('culture') ?>"><span class="glyphicon glyphicon-barcode glyphicon-white"></span>&nbsp;<?php echo $this->translate('Culturas') ?></a></li>
                    </ul>
                    <ul class="nav navbar-nav">
                        <li class="<?php if ($this->optionMenu == 'gestao') echo 'active' ?>"><a href="<?php echo $this->url('manage') ?>"><span class="glyphicon glyphicon-cog glyphicon-white"></span>&nbsp;<?php echo $this->translate('Gest&atilde;o') ?></a></li>
                    </ul>
                    <a class="btn btn-default navbar-btn navbar-right" href="<?php echo $this->url('auth', array('action' => 'login')) ?>"><?php echo $this->translate('Login') ?></a>
                </div><!--/ .nav-collapse -->
            </div><!--/ .container -->
        </nav>
        <div class="container">
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2015 - <?php echo date('Y') ?> by v2-lab Solutions Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!--/ .container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
