<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Bem vindo ao %sSistema CellaVita%s'), '<span class="cellavita-label">', '</span>') ?></h1>
    <p><?php echo sprintf($this->translate('O Sistema CellaVita proporciona o cadastro de doadores de material para cultivo de celulas tronco, assim como o acompanhamento do processo de cultura para o seu desenvolvimento. Ele também realiza o rastreamento de todo o processo, permitindo a rápida identificação, pelo lote, dos estágios de cultura anteriores e do material original de determinado doador. Para sua utilização, efetue login usando sua conta no link acima.')) ?></p>
</div>
