<div class="">
	<?php
		// Set the basic form tag
		$form->setAttribute('action', $this->url('auth', array('action' => 'login')))->prepare();
		echo $this->form()->openTag($form);
		// Prepare the login form to display
		$user = $form->get('user');
	?>
	<h2>Login</h2>
	<fieldset>
		<div class="form-group">
			<label class="col-sm-2 control-label"><?php echo sprintf($this->translate('Usuário:')); ?></label>
			<div class="col-sm-6">
				<?php echo $this->formRow($user->get('login')); ?>
				<span class="help-block"><?php echo sprintf($this->translate('Preencha com o ID do usuario')); ?></span>
			</div>
		</div>
		<div class="form-group">
			<label class="col-sm-2 control-label"><?php echo sprintf($this->translate('Senha:')); ?></label>
			<div class="col-sm-6">
				<?php echo $this->formRow($user->get('password')); ?>
				<span class="help-block"><?php echo sprintf($this->translate('Informe a senha')); ?></span>
			</div>
		</div>
	</fieldset>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-2">
			<?php echo $this->formElement($form->get('submit')); ?>
		</div>
	</div>
	<?php echo $this->form()->closeTag(); ?>
</div>
